groups:
  - name: disk_usage_alerts
    rules:
      - alert: HostDiskUtilizationTrouble
        expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes * 100 >= 80
        for: 5m
        labels:
          severity: trouble
        annotations:
          description: "Disk utilization is over 80%. The Monitor {{ $labels.instance_name }} from {{ $labels.ClientName }} account is in a TROUBLE state. The possible reason for this incident is Disk Utilization exceeds 80% filesystem {{ $labels.mountpoint }}."
          VALUE: '{{ $value }}'
          LABELS: '{{ $labels }}'
          summary: "Host is in trouble due to high disk utilization (instance {{ $labels.instance_name }}, filesystem {{ $labels.mountpoint }})"

      - alert: HostDiskUtilizationCritical
        expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes * 100 >= 90
        for: 5m
        labels:
          severity: critical
        annotations:
          description: "Disk utilization is over 90%. The Monitor {{ $labels.instance_name }} is in a CRITICAL state. The possible reason for this incident is Disk Utilization exceeds 90% filesystem {{ $labels.mountpoint }}."
          VALUE: '{{ $value }}'
          LABELS: '{{ $labels }}'
          summary: "Host is in a critical condition due to extremely high disk utilization (instance {{ $labels.instance_name }}, filesystem {{ $labels.mountpoint }})"

  - name: diskio_alerts
    rules:
      - alert: DiskIOHighCritical
        expr: rate(node_disk_written_bytes_total{device=~"^(sd.*|xv.*|nvme.*)$"}[1m]) / 1024 > 100000
        for: 5m
        labels:
          severity: critical
        annotations:
          description: "Disk I/O ({{ printf \"%.2f\" $value }} bytes/sec) on {{ $labels.instance_name }} is critically high, exceeding the threshold of 10MB/s. Immediate investigation required."
          VALUE: "{{ $value }}"
          LABELS: "{{ $labels }}"
          summary: "High disk I/O detected on {{ $labels.instance_name }}"

  - name: server_alerts
    rules:
      - alert: ServerDown
        expr: up == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          description: "Server {{ $labels.instance_name }} is down. The Monitor {{ $labels.instance_name }} is in a CRITICAL state. The possible reason for this incident is the server is not responding."
          VALUE: "{{ $value }}"
          LABELS: "{{ $labels }}"
          summary: "Server {{ $labels.instance_name }} is down"

  - name: memory_alerts
    rules:
      - alert: HostMemoryCritical
        expr: 100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) >= 90
        for: 5m
        labels:
          severity: critical
        annotations:
          description: "Node memory is running above 90%. The Monitor {{ $labels.instance_name }} is in a CRITICAL state. The possible reason for this incident is Memory Usage exceeds 90%."
          VALUE: "{{ $value }}"
          LABELS: "{{ $labels }}"
          summary: "Host is in a critical condition due to extremely low memory (instance {{ $labels.instance_name }})"

      - alert: HostMemoryTrouble
        expr: 100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) >= 80
        for: 5m
        labels:
          severity: trouble
        annotations:
          description: "Node memory is running above 80%. The Monitor {{ $labels.instance_name }} is in a TROUBLE state. The possible reason for this incident is MemoryUsage exceeds 80%."
          VALUE: "{{ $value }}"
          LABELS: "{{ $labels }}"
          summary: "Host is in trouble due to low memory (instance {{ $labels.instance_name }})"

  - name: swapmemory_alerts
    rules:
      - alert: HostHighSwapUsageCritical
        expr: 100 * (1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          description: "Swap memory usage is above 90%. The Monitor {{ $labels.instance_name }} is in a CRITICAL state. The possible reason for this incident is Swap Memory Usage exceeds 90%."
          VALUE: "{{ $value }}"
          LABELS: "{{ $labels }}"
          summary: "Host is in a critical condition due to extremely high swap memory usage (instance {{ $labels.instance_name }})"

      - alert: HostHighSwapUsageTrouble
        expr: 100 * (1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) > 80
        for: 5m
        labels:
          severity: trouble
        annotations:
          description: "Swap memory usage is above 80%. The Monitor {{ $labels.instance_name }} is in a TROUBLE state. The possible reason for this incident is Swap Memory Usage exceeds 80%."
          VALUE: "{{ $value }}"
          LABELS: "{{ $labels }}"
          summary: "Host might be in trouble due to high swap memory usage (instance {{ $labels.instance_name }})"

  - name: cpu_alerts_linux
    rules:
      - alert: CPUUtilizationTrouble
        expr: rate(node_cpu_seconds_total{mode!="idle"}[5m]) > 0.8
        for: 5m
        labels:
          severity: trouble
        annotations:
          description: "CPU usage for the instance: {{ $labels.instance_name }} is above 80%."
          VALUE: "{{ $value }}"
          LABELS: "{{ $labels }}"
          summary: "Warning: CPU usage for the instance: {{ $labels.instance_name }} is above 80%."

      - alert: CPUUtilizationCritical
        expr: rate(node_cpu_seconds_total{mode!="idle"}[5m]) > 0.9
        for: 5m
        labels:
          severity: critical
        annotations:
          description: "CPU usage for the instance: {{ $labels.instance_name }} is above 90%."
          VALUE: "{{ $value }}"
          LABELS: "{{ $labels }}"
          summary: "Critical: CPU usage for the instance: {{ $labels.instance_name }} is above 90%."

################################## Windows Alerts ##############################################################
## DiskUsage Alert
  - name: windows_drive_disk_usage
    rules:
      - alert: WindowsDiskUtilizationTrouble
        expr: ((windows_logical_disk_size_bytes - windows_logical_disk_free_bytes) / windows_logical_disk_size_bytes * 100) >= 80 
        for: 5m
        labels:
          severity: trouble
        annotations:
          description: "Disk utilization is over 80%. The Monitor {{ $labels.instance_name }} is in a TROUBLE state. The possible reason for this incident is Disk Utilization exceeds 80% filesystem {{ $labels.mountpoint }}."
          VALUE: '{{ $value }}'
          LABELS: '{{ $labels }}'
          summary: "Host is in a trouble condition due to extremely high disk utilization (instance {{ $labels.instance_name }}, filesystem {{ $labels.volume }})"

      - alert: WindowsDiskUtilizationCritical
        expr: ((windows_logical_disk_size_bytes - windows_logical_disk_free_bytes) / windows_logical_disk_size_bytes * 100) >= 90
        for: 5m
        labels:
          severity: critical
        annotations:
          description: "Disk utilization is over 90%. The Monitor {{ $labels.instance_name }} is in a CRITICAL state. The possible reason for this incident is Disk Utilization exceeds 90% filesystem {{ $labels.mountpoint }}."
          VALUE: '{{ $value }}'
          LABELS: '{{ $labels }}'
          summary: "Host is in a critical condition due to extremely high disk utilization (instance {{ $labels.instance_name }}, filesystem {{ $labels.volume }})"

## MemoryUsage
  - name:  windows_memory_usage
    rules:
      - alert: HighMemoryUsageTrouble
        expr: (100 - 100 * windows_os_physical_memory_free_bytes / windows_cs_physical_memory_bytes) >= 80
        for: 5m
        labels:
          severity: trouble
        annotations:
          description: "Memory usage is over 80%. The Monitor {{ $labels.instance_name }} is in a TROUBLE state. The possible reason for this incident is Memory Usage exceeds 80% for the last 5 minutes."
          VALUE: '{{ $value }}'
          LABELS: '{{ $labels }}'
          summary: "Host is in a trouble condition due to high memory usage on (instance {{ $labels.instance_name }}for the last 5 minutes."

      - alert: HighMemoryUsageCritical
        expr: (100 - 100 * windows_os_physical_memory_free_bytes / windows_cs_physical_memory_bytes) >= 90
        for: 5m
        labels:
          severity: critical
        annotations:
          description: "Memory usage is over 90%. The Monitor {{ $labels.instance_name }} is in a TROUBLE state. The possible reason for this incident is Memory Usage exceeds 90% for the last 5 minutes."
          VALUE: '{{ $value }}'
          LABELS: '{{ $labels }}'
          summary: "Host is in a critical condition due to high memory usage on (instance {{ $labels.instance_name }}for the last 5 minutes."

## CPUUsage
  - name: windows_cpu_usage
    rules:
      - alert: HostHighCpuLoadTrouble
        expr: 100 - (avg by (instance_name, ClientName) (rate(windows_cpu_time_total{mode="idle"}[5m])) * 100) >= 80
        for: 5m
        labels:
          severity: trouble
        annotations:
          description: "CPU load is > 80. The Monitor {{ $labels.instance_name }} is in a TROUBLE state. The possible reason for this incident is CPU load exceeds 80."
          VALUE: "{{ $value }}"
          LABELS: "{{ $labels }}"
          summary: "Host is in a trouble condition due to extremely high CPU load (instance {{ $labels.instance_name }})"

      - alert: HostHighCpuLoadCritical
        expr: 100 - (avg by (instance_name, ClientName) (rate(windows_cpu_time_total{mode="idle"}[5m])) * 100) >= 90
        for: 5m
        labels:
          severity: trouble
        annotations:
          description: "CPU load is > 90. The Monitor {{ $labels.instance_name }} is in a CRITICAL state. The possible reason for this incident is CPU load exceeds 90."
          VALUE: "{{ $value }}"
          LABELS: "{{ $labels }}"
          summary: "Host is in a critical condition due to extremely high CPU load (instance {{ $labels.instance_name }})"